### ISSUE TITLE
推荐系统案例

### ISSUE THREAD

**Issue by AnitaSherry** [xfliu1998/xfliu1998.github.io#6]
大神你好，为什么[推荐系统案例](https://xfliu1998.github.io/2022/01/18/5.7-RS-case/)中没有计算模型的准确率啊

**Comment by xfliu1998** [comment]
probability就是计算的模型针对每一个用户预测的准确率，这么长时间这些知识点已经就饭吃了🥱

**Comment by AnitaSherry** [comment]
没认真看，一直在找评估指标auc，f1这些。想处理Ali_Display_Ad_Click数据集，整个GitHub只有你和paddle处理了，paddle的我完全看不懂

**Comment by xfliu1998** [comment]
我是看的b站视频，有需要你可以看一下这个：https://www.bilibili.com/video/BV1qK4y1479r?p=1&vd_source=486265fa677326a8f53894f05277bfb9
